// GENERATED by tatara-rust-derive::NewtypeDeriveSpec.
use proc_macro::TokenStream;
use quote::quote;
use syn::{Data, DataStruct, DeriveInput, Fields, parse_macro_input};

#[proc_macro_derive(AsRefNewtype)]
pub fn derive_as_ref_newtype(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let self_name = &input.ident;

    let inner_ty = match &input.data {
        Data::Struct(DataStruct { fields: Fields::Unnamed(u), .. }) if u.unnamed.len() == 1 => {
            &u.unnamed.first().expect("one field").ty
        },
        _ => {
            return syn::Error::new_spanned(self_name, "NewtypeDerive requires a single-tuple-field struct: `pub struct W(Inner);`").to_compile_error().into();
        }
    };

    let expanded = quote! {
        impl ::std::convert::AsRef<#inner_ty> for #self_name { fn as_ref(&self) -> &#inner_ty { &self.0 } }
    };
    TokenStream::from(expanded)
}
